FROM library/ubuntu
#安裝flask 0.12, request, line-bot-sdk
USER root
RUN apt-get update
RUN apt-get install python-pip python3 -y
RUN pip install --upgrade pip
RUN pip install Flask==0.12 requests line-bot-sdk redis
RUN pip install PyMySQL
